# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "96424f6c5531bf93f3b130adc26f1511"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "Kimball-custom-pricing"
handle = "kimball-custom-pricing"

[build]
include_config_on_deploy = true
dev_store_url = "kimball-electronics-ut.myshopify.com"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
